kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-istio-certmanager
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.istio.io
    resources:
      - gateways
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - cert-manager.io
    resources:
      - certificates
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-istio-certmanager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-istio-certmanager
subjects:
  - kind: ServiceAccount
    name: operator-istio-certmanager
    namespace: istio-system